name: traffic_bots
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - abseil-cpp=20211102.0=h27087fc_1
  - absl-py=2.0.0=pyhd8ed1ab_0
  - aiohttp=3.7.0=py39h07f9747_0
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - anyio=3.5.0=py39h06a4308_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h7f8727e_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=3.0.1=py_1000
  - attrs=23.1.0=pyh71513ae_1
  - babel=2.11.0=py39h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=py39h06a4308_0
  - black=19.10b0=py_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.7.0=pyhd8ed1ab_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotli-python=1.0.9=py39h5a03fae_7
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2023.7.22=hbcca054_0
  - cachetools=5.3.2=pyhd8ed1ab_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.0=py39h4bc2ebd_0
  - chardet=3.0.4=py39h079e4ff_1008
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=py39h06a4308_0
  - contourpy=1.0.5=py39hdb19cb5_0
  - cryptography=41.0.3=py39hdda0065_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py39h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - docker-pycreds=0.4.0=py_0
  - entrypoints=0.4=py39h06a4308_0
  - exceptiongroup=1.0.4=py39h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.5.0=h6a678d5_0
  - ffmpeg=4.3.2=hca11adc_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2023.10.0=pyhca7485f_0
  - future=0.18.3=pyhd8ed1ab_0
  - giflib=5.2.1=h5eee18b_3
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.40=pyhd8ed1ab_0
  - glib=2.69.1=he621ea3_2
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - google-auth=2.23.4=pyhca7485f_0
  - grpc-cpp=1.48.2=he1ff14a_1
  - grpcio=1.48.2=py39he1ff14a_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h5py=3.9.0=py39he06866b_0
  - hdf5=1.12.1=h2b7332f_3
  - hydra-core=1.3.2=pyhd8ed1ab_0
  - icu=73.1=h6a678d5_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_resources=6.1.1=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.25.0=py39h2f386ee_0
  - ipython=8.15.0=py39h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=8.0.4=py39h06a4308_0
  - jedi=0.18.1=py39h06a4308_1
  - jinja2=3.1.2=py39h06a4308_0
  - joblib=1.2.0=py39h06a4308_0
  - jpeg=9e=h5eee18b_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py39h06a4308_0
  - jsonschema-specifications=2023.7.1=py39h06a4308_0
  - jupyter=1.0.0=py39h06a4308_8
  - jupyter_client=7.4.9=py39h06a4308_0
  - jupyter_console=6.6.3=py39h06a4308_0
  - jupyter_core=5.5.0=py39h06a4308_0
  - jupyter_server=1.23.4=py39h06a4308_0
  - jupyterlab=3.3.2=pyhd3eb1b0_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.25.1=py39h06a4308_0
  - jupyterlab_widgets=3.0.5=py39h06a4308_0
  - kiwisolver=1.4.4=py39h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.4.0=h251f7ec_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libidn2=2.3.4=h5eee18b_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.15=hdbd6064_1
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h7f98852_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.44.2=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hf1b16e4_1
  - lightning-utilities=0.9.0=pyhd8ed1ab_0
  - lz4-c=1.9.4=h6a678d5_0
  - markdown=3.5.1=pyhd8ed1ab_0
  - markupsafe=2.1.1=py39hb9d737c_1
  - matplotlib=3.8.0=py39h06a4308_0
  - matplotlib-base=3.8.0=py39h1128e8f_0
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - mistune=2.0.4=py39h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.8=py39h5eee18b_0
  - mkl_random=1.2.4=py39hdb19cb5_0
  - multidict=6.0.2=py39hb9d737c_1
  - munkres=1.1.4=py_0
  - mypy_extensions=1.0.0=py39h06a4308_0
  - mysql=5.7.24=h721c034_2
  - nbclassic=0.5.5=py39h06a4308_0
  - nbclient=0.8.0=py39h06a4308_0
  - nbconvert=7.10.0=py39h06a4308_0
  - nbformat=5.9.2=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py39h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - notebook=6.5.4=py39h06a4308_1
  - notebook-shim=0.2.3=py39h06a4308_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.12=h7f8727e_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathspec=0.10.3=py39h06a4308_0
  - pathtools=0.1.2=py_1
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.0.1=py39ha6cbd5a_0
  - pip=23.3=py39h06a4308_0
  - platformdirs=3.10.0=py39h06a4308_0
  - ply=3.11=py39h06a4308_0
  - prometheus_client=0.14.1=py39h06a4308_0
  - prompt-toolkit=3.0.36=py39h06a4308_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - protobuf=3.20.3=py39h6a678d5_0
  - psutil=5.9.0=py39h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.5.0=pyhd8ed1ab_0
  - pyasn1-modules=0.3.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydeprecate=0.3.1=pyhd8ed1ab_0
  - pygments=2.15.1=py39h06a4308_1
  - pyjwt=2.8.0=pyhd8ed1ab_0
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pyparsing=3.0.9=py39h06a4308_0
  - pyqt=5.15.10=py39h6a678d5_0
  - pyqt5-sip=12.13.0=py39h5eee18b_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.18=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py39h06a4308_0
  - python_abi=3.9=2_cp39
  - pytorch=1.11.0=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-lightning=1.5.8=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=py39h06a4308_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py39hb9d737c_4
  - pyzmq=23.2.0=py39h6a678d5_0
  - qt-main=5.15.2=h53bd1ea_10
  - qtconsole=5.4.2=py39h06a4308_0
  - qtpy=2.2.0=py39h06a4308_0
  - re2=2022.04.01=h27087fc_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py39h06a4308_0
  - regex=2023.10.3=py39h5eee18b_0
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rpds-py=0.10.6=py39hb02cf49_0
  - rsa=4.9=pyhd8ed1ab_0
  - scikit-learn=1.3.0=py39h1128e8f_0
  - scipy=1.11.3=py39h5f9d8c6_0
  - send2trash=1.8.2=py39h06a4308_0
  - sentry-sdk=1.35.0=pyhd8ed1ab_0
  - setproctitle=1.1.10=py39h3811e60_1004
  - setuptools=68.0.0=py39h06a4308_0
  - sip=6.7.12=py39h6a678d5_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - sniffio=1.2.0=py39h06a4308_1
  - soupsieve=2.5=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard-data-server=0.7.0=py39h52d8a92_0
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - terminado=0.17.1=py39h06a4308_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tinycss2=1.2.1=py39h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py39h06a4308_0
  - torchmetrics=1.2.0=pyhd8ed1ab_0
  - tornado=6.3.3=py39h5eee18b_0
  - tqdm=4.65.0=py39hb070fc8_0
  - traitlets=5.7.1=py39h06a4308_0
  - transforms3d=0.4.1=pyhd8ed1ab_0
  - typed-ast=1.4.3=py39h7f8727e_1
  - typing-extensions=4.7.1=py39h06a4308_0
  - typing_extensions=4.7.1=py39h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=2.1.0=pyhd8ed1ab_0
  - wandb=0.15.12=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39h06a4308_1
  - websocket-client=0.58.0=py39h06a4308_4
  - werkzeug=3.0.1=pyhd8ed1ab_0
  - wheel=0.41.2=py39h06a4308_0
  - widgetsnbextension=4.0.5=py39h06a4308_0
  - x264=1!161.3030=h7f98852_1
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.7.2=py39hb9d737c_2
  - zeromq=4.3.4=h2531618_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - astunparse==1.6.3
      - click==8.0.2
      - cloudpickle==3.0.0
      - dm-tree==0.1.8
      - flatbuffers==23.5.26
      - gast==0.4.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - jax==0.4.28
      - keras==2.12.0
      - libclang==16.0.6
      - ml-dtypes==0.4.0
      - numpy==1.22.0
      - opencv-python==4.8.1.78
      - opt-einsum==3.3.0
      - tensorboard==2.12.3
      - tensorflow-cpu==2.12.0
      - tensorflow-estimator==2.12.0
      - tensorflow-io-gcs-filesystem==0.37.0
      - tensorflow-probability==0.19.0
      - termcolor==2.3.0
      - wrapt==1.14.1